# Distribuição de Frequência
## Regras de Associação

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('CSVs/census.csv')
df.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [3]:
def calc_classes(classes):
    return np.insert(classes, 0, classes[0] - (classes[1]-classes[0]))

In [4]:
freq, classes = np.histogram(df['age'], bins='sturges')
freq, classes, len(classes)

(array([3130, 4066, 3376, 4353, 3399, 3876, 2722, 2716, 1924, 1225,  917,
         389,  273,   96,   51,   48], dtype=int64),
 array([17.    , 21.5625, 26.125 , 30.6875, 35.25  , 39.8125, 44.375 ,
        48.9375, 53.5   , 58.0625, 62.625 , 67.1875, 71.75  , 76.3125,
        80.875 , 85.4375, 90.    ]),
 17)

In [5]:
classes

array([17.    , 21.5625, 26.125 , 30.6875, 35.25  , 39.8125, 44.375 ,
       48.9375, 53.5   , 58.0625, 62.625 , 67.1875, 71.75  , 76.3125,
       80.875 , 85.4375, 90.    ])

In [6]:
classes = calc_classes(classes)
labels = [f'AG_{classes[i]}-{classes[i + 1]}' for i in range(len(classes)-1)]
df['age'] = pd.cut(df['age'], bins=classes,
                  labels=labels)
df.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
0,AG_35.25-39.8125,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,AG_48.9375-53.5,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,AG_35.25-39.8125,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,AG_48.9375-53.5,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,AG_26.125-30.6875,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [7]:
freq, classes = np.histogram(df['final-weight'], bins='sturges')
freq, classes, len(classes)

(array([ 6244, 13292,  8090,  3328,  1106,   306,   101,    54,    15,
            9,     3,     5,     3,     2,     1,     2], dtype=int64),
 array([  12285.  ,  104311.25,  196337.5 ,  288363.75,  380390.  ,
         472416.25,  564442.5 ,  656468.75,  748495.  ,  840521.25,
         932547.5 , 1024573.75, 1116600.  , 1208626.25, 1300652.5 ,
        1392678.75, 1484705.  ]),
 17)

In [8]:
classes = calc_classes(classes)
labels = [f'FW_{classes[i]}-{classes[i + 1]}' for i in range(len(classes)-1)]
df['final-weight'] = pd.cut(df['final-weight'], bins=classes,
                  labels=labels)
df.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
0,AG_35.25-39.8125,State-gov,FW_12285.0-104311.25,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,AG_48.9375-53.5,Self-emp-not-inc,FW_12285.0-104311.25,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,AG_35.25-39.8125,Private,FW_196337.5-288363.75,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,AG_48.9375-53.5,Private,FW_196337.5-288363.75,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,AG_26.125-30.6875,Private,FW_288363.75-380390.0,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [9]:
freq, classes = np.histogram(df['education-num'], bins='sturges')
freq, classes, len(classes)

(array([   51,   168,   333,   646,   514,   933,  1175,   433, 10501,
         7291,  1382,  1067,  5355,  1723,   576,   413], dtype=int64),
 array([ 1.    ,  1.9375,  2.875 ,  3.8125,  4.75  ,  5.6875,  6.625 ,
         7.5625,  8.5   ,  9.4375, 10.375 , 11.3125, 12.25  , 13.1875,
        14.125 , 15.0625, 16.    ]),
 17)

In [10]:
classes = calc_classes(classes)
labels = [f'EN_{classes[i]}-{classes[i + 1]}' for i in range(len(classes)-1)]
df['education-num'] = pd.cut(df['education-num'], bins=classes,
                  labels=labels)
df.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
0,AG_35.25-39.8125,State-gov,FW_12285.0-104311.25,Bachelors,EN_12.25-13.1875,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,AG_48.9375-53.5,Self-emp-not-inc,FW_12285.0-104311.25,Bachelors,EN_12.25-13.1875,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,AG_35.25-39.8125,Private,FW_196337.5-288363.75,HS-grad,EN_8.5-9.4375,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,AG_48.9375-53.5,Private,FW_196337.5-288363.75,11th,EN_6.625-7.5625,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,AG_26.125-30.6875,Private,FW_288363.75-380390.0,Bachelors,EN_12.25-13.1875,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [11]:
freq, classes = np.histogram(df['capital-gain'], bins='sturges')
freq, classes, len(classes)

(array([31100,   754,   454,    38,    49,     5,     2,     0,     0,
            0,     0,     0,     0,     0,     0,   159], dtype=int64),
 array([    0.    ,  6249.9375, 12499.875 , 18749.8125, 24999.75  ,
        31249.6875, 37499.625 , 43749.5625, 49999.5   , 56249.4375,
        62499.375 , 68749.3125, 74999.25  , 81249.1875, 87499.125 ,
        93749.0625, 99999.    ]),
 17)

In [12]:
classes = calc_classes(classes)
labels = [f'CG_{classes[i]}-{classes[i + 1]}' for i in range(len(classes)-1)]
df['capital-gain'] = pd.cut(df['capital-gain'], bins=classes,
                  labels=labels)
df.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
0,AG_35.25-39.8125,State-gov,FW_12285.0-104311.25,Bachelors,EN_12.25-13.1875,Never-married,Adm-clerical,Not-in-family,White,Male,CG_0.0-6249.9375,0,40,United-States,<=50K
1,AG_48.9375-53.5,Self-emp-not-inc,FW_12285.0-104311.25,Bachelors,EN_12.25-13.1875,Married-civ-spouse,Exec-managerial,Husband,White,Male,CG_-6249.9375-0.0,0,13,United-States,<=50K
2,AG_35.25-39.8125,Private,FW_196337.5-288363.75,HS-grad,EN_8.5-9.4375,Divorced,Handlers-cleaners,Not-in-family,White,Male,CG_-6249.9375-0.0,0,40,United-States,<=50K
3,AG_48.9375-53.5,Private,FW_196337.5-288363.75,11th,EN_6.625-7.5625,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,CG_-6249.9375-0.0,0,40,United-States,<=50K
4,AG_26.125-30.6875,Private,FW_288363.75-380390.0,Bachelors,EN_12.25-13.1875,Married-civ-spouse,Prof-specialty,Wife,Black,Female,CG_-6249.9375-0.0,0,40,Cuba,<=50K

In [13]:
freq, classes = np.histogram(df['capital-loos'], bins='sturges')
freq, classes, len(classes)

(array([31047,     6,    17,     8,    20,   269,   659,   305,   180,
           27,    12,     2,     0,     4,     2,     3], dtype=int64),
 array([   0.  ,  272.25,  544.5 ,  816.75, 1089.  , 1361.25, 1633.5 ,
        1905.75, 2178.  , 2450.25, 2722.5 , 2994.75, 3267.  , 3539.25,
        3811.5 , 4083.75, 4356.  ]),
 17)

In [14]:
classes = calc_classes(classes)
labels = [f'CL_{classes[i]}-{classes[i + 1]}' for i in range(len(classes)-1)]
df['capital-loos'] = pd.cut(df['capital-loos'], bins=classes,
                  labels=labels)
df.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
0,AG_35.25-39.8125,State-gov,FW_12285.0-104311.25,Bachelors,EN_12.25-13.1875,Never-married,Adm-clerical,Not-in-family,White,Male,CG_0.0-6249.9375,CL_-272.25-0.0,40,United-States,<=50K
1,AG_48.9375-53.5,Self-emp-not-inc,FW_12285.0-104311.25,Bachelors,EN_12.25-13.1875,Married-civ-spouse,Exec-managerial,Husband,White,Male,CG_-6249.9375-0.0,CL_-272.25-0.0,13,United-States,<=50K
2,AG_35.25-39.8125,Private,FW_196337.5-288363.75,HS-grad,EN_8.5-9.4375,Divorced,Handlers-cleaners,Not-in-family,White,Male,CG_-6249.9375-0.0,CL_-272.25-0.0,40,United-States,<=50K
3,AG_48.9375-53.5,Private,FW_196337.5-288363.75,11th,EN_6.625-7.5625,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,CG_-6249.9375-0.0,CL_-272.25-0.0,40,United-States,<=50K
4,AG_26.125-30.6875,Private,FW_288363.75-380390.0,Bachelors,EN_12.25-13.1875,Married-civ-spouse,Prof-specialty,Wife,Black,Female,CG_-6249.9375-0.0,CL_-272.25-0.0,40,Cuba,<=50K

In [15]:
freq, classes = np.histogram(df['hour-per-week'], bins='sturges')
freq, classes, len(classes)

(array([  295,   648,   761,  2239,  1307,  1999, 16137,  2713,  3827,
         1545,   301,   365,   216,    64,    38,   106], dtype=int64),
 array([ 1.   ,  7.125, 13.25 , 19.375, 25.5  , 31.625, 37.75 , 43.875,
        50.   , 56.125, 62.25 , 68.375, 74.5  , 80.625, 86.75 , 92.875,
        99.   ]),
 17)

In [16]:
classes = calc_classes(classes)
labels = [f'HW_{classes[i]}-{classes[i + 1]}' for i in range(len(classes)-1)]
df['hour-per-week'] = pd.cut(df['hour-per-week'], bins=classes,
                  labels=labels)
df.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
0,AG_35.25-39.8125,State-gov,FW_12285.0-104311.25,Bachelors,EN_12.25-13.1875,Never-married,Adm-clerical,Not-in-family,White,Male,CG_0.0-6249.9375,CL_-272.25-0.0,HW_37.75-43.875,United-States,<=50K
1,AG_48.9375-53.5,Self-emp-not-inc,FW_12285.0-104311.25,Bachelors,EN_12.25-13.1875,Married-civ-spouse,Exec-managerial,Husband,White,Male,CG_-6249.9375-0.0,CL_-272.25-0.0,HW_7.125-13.25,United-States,<=50K
2,AG_35.25-39.8125,Private,FW_196337.5-288363.75,HS-grad,EN_8.5-9.4375,Divorced,Handlers-cleaners,Not-in-family,White,Male,CG_-6249.9375-0.0,CL_-272.25-0.0,HW_37.75-43.875,United-States,<=50K
3,AG_48.9375-53.5,Private,FW_196337.5-288363.75,11th,EN_6.625-7.5625,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,CG_-6249.9375-0.0,CL_-272.25-0.0,HW_37.75-43.875,United-States,<=50K
4,AG_26.125-30.6875,Private,FW_288363.75-380390.0,Bachelors,EN_12.25-13.1875,Married-civ-spouse,Prof-specialty,Wife,Black,Female,CG_-6249.9375-0.0,CL_-272.25-0.0,HW_37.75-43.875,Cuba,<=50K

In [17]:
df_apriori = df[['age','workclass','final-weight','education','education-num',
                 'marital-status','relationship','race','capital-gain','capital-loos',
                 'hour-per-week','occupation', 'native-country','income']]

In [18]:
df_apriori.shape

(32561, 14)

In [19]:
df_apriori = df_apriori.sample(n = 1000)
df_apriori.shape

(1000, 14)

In [20]:
transacoes = []
for i in range(df_apriori.shape[0]):
    transacoes.append([str(df_apriori.values[i, j]) for j in range(df_apriori.shape[1])])

In [21]:
len(transacoes)

1000

In [22]:
transacoes[:2]

[['AG_62.625-67.1875',
  ' ?',
  'FW_12285.0-104311.25',
  ' HS-grad',
  'EN_8.5-9.4375',
  ' Widowed',
  ' Not-in-family',
  ' White',
  'CG_-6249.9375-0.0',
  'CL_-272.25-0.0',
  'HW_37.75-43.875',
  ' ?',
  ' United-States',
  ' <=50K'],
 ['AG_17.0-21.5625',
  ' Local-gov',
  'FW_12285.0-104311.25',
  ' Some-college',
  'EN_9.4375-10.375',
  ' Never-married',
  ' Not-in-family',
  ' White',
  'CG_-6249.9375-0.0',
  'CL_1905.75-2178.0',
  'HW_37.75-43.875',
  ' Other-service',
  ' United-States',
  ' <=50K']]

In [23]:
!pip install apyori

Requirement already satisfied: apyori in c:\programdata\anaconda3\lib\site-packages (1.1.2)

WARNING: You are using pip version 20.1; however, version 20.3.3 is available.
You should consider upgrading via the 'C:\ProgramData\Anaconda3\python.exe -m pip install --upgrade pip' command.

In [24]:
from apyori import apriori

In [25]:
rules = apriori(transacoes, min_support = 0.3, min_confidence = 0.5, min_lift=2)
result = list(rules)
len(result)

13

In [26]:
print(*result, sep='\n\n')

RelationRecord(items=frozenset({'EN_8.5-9.4375', ' HS-grad'}), support=0.308, ordered_statistics=[OrderedStatistic(items_base=frozenset({' HS-grad'}), items_add=frozenset({'EN_8.5-9.4375'}), confidence=1.0, lift=3.2467532467532467), OrderedStatistic(items_base=frozenset({'EN_8.5-9.4375'}), items_add=frozenset({' HS-grad'}), confidence=1.0, lift=3.2467532467532467)])

RelationRecord(items=frozenset({' Husband', ' Married-civ-spouse'}), support=0.398, ordered_statistics=[OrderedStatistic(items_base=frozenset({' Husband'}), items_add=frozenset({' Married-civ-spouse'}), confidence=1.0, lift=2.1739130434782608), OrderedStatistic(items_base=frozenset({' Married-civ-spouse'}), items_add=frozenset({' Husband'}), confidence=0.8652173913043478, lift=2.1739130434782608)])

RelationRecord(items=frozenset({' Husband', ' United-States', ' Married-civ-spouse'}), support=0.357, ordered_statistics=[OrderedStatistic(items_base=frozenset({' Husband'}), items_add=frozenset({' United-States', ' Married-civ-spouse'}), confidence=0.8969849246231155, lift=2.1771478752988243), OrderedStatistic(items_base=frozenset({' Married-civ-spouse'}), items_add=frozenset({' Husband', ' United-States'}), confidence=0.7760869565217391, lift=2.1739130434782608), OrderedStatistic(items_base=frozenset({' Husband', ' United-States'}), items_add=frozenset({' Married-civ-spouse'}), confidence=1.0, lift=2.1739130434782608), OrderedStatistic(items_base=frozenset({' United-States', ' Married-civ-spouse'}), items_add=frozenset({' Husband'}), confidence=0.8665048543689321, lift=2.1771478752988243)])

RelationRecord(items=frozenset({' Husband', ' White', ' Married-civ-spouse'}), support=0.355, ordered_statistics=[OrderedStatistic(items_base=frozenset({' Husband'}), items_add=frozenset({' White', ' Married-civ-spouse'}), confidence=0.8919597989949748, lift=2.18617597792886), OrderedStatistic(items_base=frozenset({' Married-civ-spouse'}), items_add=frozenset({' Husband', ' White'}), confidence=0.7717391304347825, lift=2.1739130434782608), OrderedStatistic(items_base=frozenset({' Husband', ' White'}), items_add=frozenset({' Married-civ-spouse'}), confidence=1.0, lift=2.1739130434782608), OrderedStatistic(items_base=frozenset({' White', ' Married-civ-spouse'}), items_add=frozenset({' Husband'}), confidence=0.8700980392156863, lift=2.18617597792886)])

RelationRecord(items=frozenset({' Husband', 'CG_-6249.9375-0.0', ' Married-civ-spouse'}), support=0.356, ordered_statistics=[OrderedStatistic(items_base=frozenset({' Husband'}), items_add=frozenset({' Married-civ-spouse', 'CG_-6249.9375-0.0'}), confidence=0.8944723618090451, lift=2.1710494218666145), OrderedStatistic(items_base=frozenset({' Married-civ-spouse'}), items_add=frozenset({' Husband', 'CG_-6249.9375-0.0'}), confidence=0.7739130434782608, lift=2.1739130434782608), OrderedStatistic(items_base=frozenset({' Husband', 'CG_-6249.9375-0.0'}), items_add=frozenset({' Married-civ-spouse'}), confidence=1.0, lift=2.1739130434782608), OrderedStatistic(items_base=frozenset({'CG_-6249.9375-0.0', ' Married-civ-spouse'}), items_add=frozenset({' Husband'}), confidence=0.8640776699029127, lift=2.1710494218666145)])

RelationRecord(items=frozenset({' Husband', 'CL_-272.25-0.0', ' Married-civ-spouse'}), support=0.375, ordered_statistics=[OrderedStatistic(items_base=frozenset({' Husband'}), items_add=frozenset({'CL_-272.25-0.0', ' Married-civ-spouse'}), confidence=0.9422110552763818, lift=2.1709932149225386), OrderedStatistic(items_base=frozenset({' Married-civ-spouse'}), items_add=frozenset({' Husband', 'CL_-272.25-0.0'}), confidence=0.8152173913043478, lift=2.1739130434782608), OrderedStatistic(items_base=frozenset({' Husband', 'CL_-272.25-0.0'}), items_add=frozenset({' Married-civ-spouse'}), confidence=1.0, lift=2.1739130434782608), OrderedStatistic(items_base=frozenset({'CL_-272.25-0.0', ' Married-civ-spouse'}), items_add=frozenset({' Husband'}), confidence=0.8640552995391705, lift=2.1709932149225386)])

RelationRecord(items=frozenset({' Husband', ' United-States', ' White', ' Married-civ-spouse'}), support=0.326, ordered_statistics=[OrderedStatistic(items_base=frozenset({' Husband'}), items_add=frozenset({' United-States', ' White', ' Married-civ-spouse'}), confidence=0.8190954773869347, lift=2.190094859323355), OrderedStatistic(items_base=frozenset({' Married-civ-spouse'}), items_add=frozenset({' Husband', ' United-States', ' White'}), confidence=0.7086956521739131, lift=2.1739130434782608), OrderedStatistic(items_base=frozenset({' Husband', ' United-States'}), items_add=frozenset({' White', ' Married-civ-spouse'}), confidence=0.9131652661064427, lift=2.238150162025595), OrderedStatistic(items_base=frozenset({' Husband', ' White'}), items_add=frozenset({' United-States', ' Married-civ-spouse'}), confidence=0.9183098591549297, lift=2.2289074251333245), OrderedStatistic(items_base=frozenset({' United-States', ' Married-civ-spouse'}), items_add=frozenset({' Husband', ' White'}), confidence=0.7912621359223302, lift=2.2289074251333245), OrderedStatistic(items_base=frozenset({' White', ' Married-civ-spouse'}), items_add=frozenset({' Husband', ' United-States'}), confidence=0.7990196078431373, lift=2.238150162025595), OrderedStatistic(items_base=frozenset({' Husband', ' United-States', ' White'}), items_add=frozenset({' Married-civ-spouse'}), confidence=1.0, lift=2.1739130434782608), OrderedStatistic(items_base=frozenset({' United-States', ' White', ' Married-civ-spouse'}), items_add=frozenset({' Husband'}), confidence=0.8716577540106952, lift=2.190094859323355)])

RelationRecord(items=frozenset({' Husband', ' United-States', 'CG_-6249.9375-0.0', ' Married-civ-spouse'}), support=0.32, ordered_statistics=[OrderedStatistic(items_base=frozenset({' Husband'}), items_add=frozenset({' United-States', ' Married-civ-spouse', 'CG_-6249.9375-0.0'}), confidence=0.8040201005025125, lift=2.178916261524424), OrderedStatistic(items_base=frozenset({' Married-civ-spouse'}), items_add=frozenset({' Husband', ' United-States', 'CG_-6249.9375-0.0'}), confidence=0.6956521739130435, lift=2.1739130434782608), OrderedStatistic(items_base=frozenset({' Husband', ' United-States'}), items_add=frozenset({' Married-civ-spouse', 'CG_-6249.9375-0.0'}), confidence=0.896358543417367, lift=2.1756275325664247), OrderedStatistic(items_base=frozenset({' Husband', 'CG_-6249.9375-0.0'}), items_add=frozenset({' United-States', ' Married-civ-spouse'}), confidence=0.8988764044943821, lift=2.181738845860151), OrderedStatistic(items_base=frozenset({' United-States', ' Married-civ-spouse'}), items_add=frozenset({' Husband', 'CG_-6249.9375-0.0'}), confidence=0.7766990291262137, lift=2.181738845860151), OrderedStatistic(items_base=frozenset({'CG_-6249.9375-0.0', ' Married-civ-spouse'}), items_add=frozenset({' Husband', ' United-States'}), confidence=0.7766990291262137, lift=2.175627532566425), OrderedStatistic(items_base=frozenset({' Husband', ' United-States', 'CG_-6249.9375-0.0'}), items_add=frozenset({' Married-civ-spouse'}), confidence=1.0, lift=2.1739130434782608), OrderedStatistic(items_base=frozenset({' United-States', 'CG_-6249.9375-0.0', ' Married-civ-spouse'}), items_add=frozenset({' Husband'}), confidence=0.8672086720867209, lift=2.1789162615244244)])

RelationRecord(items=frozenset({' Husband', ' United-States', 'CL_-272.25-0.0', ' Married-civ-spouse'}), support=0.335, ordered_statistics=[OrderedStatistic(items_base=frozenset({' Husband'}), items_add=frozenset({' United-States', 'CL_-272.25-0.0', ' Married-civ-spouse'}), confidence=0.8417085427135679, lift=2.1749574747120617), OrderedStatistic(items_base=frozenset({' Married-civ-spouse'}), items_add=frozenset({' Husband', ' United-States', 'CL_-272.25-0.0'}), confidence=0.7282608695652174, lift=2.1739130434782608), OrderedStatistic(items_base=frozenset({' Husband', ' United-States'}), items_add=frozenset({'CL_-272.25-0.0', ' Married-civ-spouse'}), confidence=0.9383753501400561, lift=2.162155184654507), OrderedStatistic(items_base=frozenset({' Husband', 'CL_-272.25-0.0'}), items_add=frozenset({' United-States', ' Married-civ-spouse'}), confidence=0.8933333333333334, lift=2.168284789644013), OrderedStatistic(items_base=frozenset({' United-States', ' Married-civ-spouse'}), items_add=frozenset({' Husband', 'CL_-272.25-0.0'}), confidence=0.8131067961165049, lift=2.168284789644013), OrderedStatistic(items_base=frozenset({'CL_-272.25-0.0', ' Married-civ-spouse'}), items_add=frozenset({' Husband', ' United-States'}), confidence=0.771889400921659, lift=2.162155184654507), OrderedStatistic(items_base=frozenset({' Husband', ' United-States', 'CL_-272.25-0.0'}), items_add=frozenset({' Married-civ-spouse'}), confidence=1.0, lift=2.1739130434782608), OrderedStatistic(items_base=frozenset({' United-States', 'CL_-272.25-0.0', ' Married-civ-spouse'}), items_add=frozenset({' Husband'}), confidence=0.8656330749354005, lift=2.1749574747120617)])

RelationRecord(items=frozenset({' Husband', 'CG_-6249.9375-0.0', ' White', ' Married-civ-spouse'}), support=0.319, ordered_statistics=[OrderedStatistic(items_base=frozenset({' Husband'}), items_add=frozenset({' Married-civ-spouse', ' White', 'CG_-6249.9375-0.0'}), confidence=0.8015075376884422, lift=2.183944244382676), OrderedStatistic(items_base=frozenset({' Married-civ-spouse'}), items_add=frozenset({' Husband', ' White', 'CG_-6249.9375-0.0'}), confidence=0.6934782608695652, lift=2.1739130434782608), OrderedStatistic(items_base=frozenset({' Husband', ' White'}), items_add=frozenset({' Married-civ-spouse', 'CG_-6249.9375-0.0'}), confidence=0.8985915492957747, lift=2.181047449747026), OrderedStatistic(items_base=frozenset({' Husband', 'CG_-6249.9375-0.0'}), items_add=frozenset({' White', ' Married-civ-spouse'}), confidence=0.8960674157303371, lift=2.1962436660057283), OrderedStatistic(items_base=frozenset({' White', ' Married-civ-spouse'}), items_add=frozenset({' Husband', 'CG_-6249.9375-0.0'}), confidence=0.7818627450980393, lift=2.1962436660057287), OrderedStatistic(items_base=frozenset({'CG_-6249.9375-0.0', ' Married-civ-spouse'}), items_add=frozenset({' Husband', ' White'}), confidence=0.7742718446601943, lift=2.1810474497470262), OrderedStatistic(items_base=frozenset({' Husband', ' White', 'CG_-6249.9375-0.0'}), items_add=frozenset({' Married-civ-spouse'}), confidence=1.0, lift=2.1739130434782608), OrderedStatistic(items_base=frozenset({'CG_-6249.9375-0.0', ' White', ' Married-civ-spouse'}), items_add=frozenset({' Husband'}), confidence=0.8692098092643052, lift=2.183944244382676)])

RelationRecord(items=frozenset({' Husband', ' White', 'CL_-272.25-0.0', ' Married-civ-spouse'}), support=0.332, ordered_statistics=[OrderedStatistic(items_base=frozenset({' Husband'}), items_add=frozenset({' White', 'CL_-272.25-0.0', ' Married-civ-spouse'}), confidence=0.8341708542713567, lift=2.183693335788892), OrderedStatistic(items_base=frozenset({' Married-civ-spouse'}), items_add=frozenset({' Husband', ' White', 'CL_-272.25-0.0'}), confidence=0.7217391304347827, lift=2.1739130434782608), OrderedStatistic(items_base=frozenset({' Husband', ' White'}), items_add=frozenset({'CL_-272.25-0.0', ' Married-civ-spouse'}), confidence=0.9352112676056339, lift=2.154864671902382), OrderedStatistic(items_base=frozenset({' Husband', 'CL_-272.25-0.0'}), items_add=frozenset({' White', ' Married-civ-spouse'}), confidence=0.8853333333333334, lift=2.169934640522876), OrderedStatistic(items_base=frozenset({' White', ' Married-civ-spouse'}), items_add=frozenset({' Husband', 'CL_-272.25-0.0'}), confidence=0.8137254901960785, lift=2.169934640522876), OrderedStatistic(items_base=frozenset({'CL_-272.25-0.0', ' Married-civ-spouse'}), items_add=frozenset({' Husband', ' White'}), confidence=0.7649769585253456, lift=2.154864671902382), OrderedStatistic(items_base=frozenset({' Husband', ' White', 'CL_-272.25-0.0'}), items_add=frozenset({' Married-civ-spouse'}), confidence=1.0, lift=2.1739130434782608), OrderedStatistic(items_base=frozenset({' White', 'CL_-272.25-0.0', ' Married-civ-spouse'}), items_add=frozenset({' Husband'}), confidence=0.8691099476439791, lift=2.183693335788892)])

RelationRecord(items=frozenset({' Husband', 'CG_-6249.9375-0.0', 'CL_-272.25-0.0', ' Married-civ-spouse'}), support=0.333, ordered_statistics=[OrderedStatistic(items_base=frozenset({' Husband'}), items_add=frozenset({' Married-civ-spouse', 'CL_-272.25-0.0', 'CG_-6249.9375-0.0'}), confidence=0.8366834170854272, lift=2.1675736193922983), OrderedStatistic(items_base=frozenset({' Married-civ-spouse'}), items_add=frozenset({' Husband', 'CL_-272.25-0.0', 'CG_-6249.9375-0.0'}), confidence=0.7239130434782609, lift=2.1739130434782608), OrderedStatistic(items_base=frozenset({' Husband', 'CG_-6249.9375-0.0'}), items_add=frozenset({'CL_-272.25-0.0', ' Married-civ-spouse'}), confidence=0.9353932584269664, lift=2.1552840055920885), OrderedStatistic(items_base=frozenset({' Husband', 'CL_-272.25-0.0'}), items_add=frozenset({' Married-civ-spouse', 'CG_-6249.9375-0.0'}), confidence=0.888, lift=2.1553398058252426), OrderedStatistic(items_base=frozenset({'CG_-6249.9375-0.0', ' Married-civ-spouse'}), items_add=frozenset({' Husband', 'CL_-272.25-0.0'}), confidence=0.8082524271844661, lift=2.155339805825243), OrderedStatistic(items_base=frozenset({'CL_-272.25-0.0', ' Married-civ-spouse'}), items_add=frozenset({' Husband', 'CG_-6249.9375-0.0'}), confidence=0.7672811059907835, lift=2.1552840055920885), OrderedStatistic(items_base=frozenset({' Husband', 'CL_-272.25-0.0', 'CG_-6249.9375-0.0'}), items_add=frozenset({' Married-civ-spouse'}), confidence=1.0, lift=2.1739130434782608), OrderedStatistic(items_base=frozenset({'CG_-6249.9375-0.0', 'CL_-272.25-0.0', ' Married-civ-spouse'}), items_add=frozenset({' Husband'}), confidence=0.8626943005181348, lift=2.1675736193922983)])

RelationRecord(items=frozenset({'CL_-272.25-0.0', ' Husband', ' United-States', ' White', ' Married-civ-spouse'}), support=0.304, ordered_statistics=[OrderedStatistic(items_base=frozenset({' Husband'}), items_add=frozenset({' United-States', ' White', 'CL_-272.25-0.0', ' Married-civ-spouse'}), confidence=0.7638190954773869, lift=2.1885933967833435), OrderedStatistic(items_base=frozenset({' Married-civ-spouse'}), items_add=frozenset({' Husband', ' United-States', ' White', 'CL_-272.25-0.0'}), confidence=0.6608695652173913, lift=2.1739130434782608), OrderedStatistic(items_base=frozenset({' Husband', ' United-States'}), items_add=frozenset({' White', 'CL_-272.25-0.0', ' Married-civ-spouse'}), confidence=0.8515406162464986, lift=2.2291639168756507), OrderedStatistic(items_base=frozenset({' Husband', ' White'}), items_add=frozenset({' United-States', 'CL_-272.25-0.0', ' Married-civ-spouse'}), confidence=0.856338028169014, lift=2.2127597627106304), OrderedStatistic(items_base=frozenset({' Husband', 'CL_-272.25-0.0'}), items_add=frozenset({' United-States', ' White', ' Married-civ-spouse'}), confidence=0.8106666666666666, lift=2.1675579322638145), OrderedStatistic(items_base=frozenset({' United-States', ' Married-civ-spouse'}), items_add=frozenset({' Husband', ' White', 'CL_-272.25-0.0'}), confidence=0.7378640776699029, lift=2.222482161656334), OrderedStatistic(items_base=frozenset({' White', ' Married-civ-spouse'}), items_add=frozenset({' Husband', ' United-States', 'CL_-272.25-0.0'}), confidence=0.7450980392156863, lift=2.2241732513901082), OrderedStatistic(items_base=frozenset({'CL_-272.25-0.0', ' Married-civ-spouse'}), items_add=frozenset({' Husband', ' United-States', ' White'}), confidence=0.7004608294930875, lift=2.14865285120579), OrderedStatistic(items_base=frozenset({' Husband', ' United-States', ' White'}), items_add=frozenset({'CL_-272.25-0.0', ' Married-civ-spouse'}), confidence=0.9325153374233128, lift=2.14865285120579), OrderedStatistic(items_base=frozenset({' Husband', ' United-States', 'CL_-272.25-0.0'}), items_add=frozenset({' White', ' Married-civ-spouse'}), confidence=0.9074626865671641, lift=2.2241732513901082), OrderedStatistic(items_base=frozenset({' Husband', ' White', 'CL_-272.25-0.0'}), items_add=frozenset({' United-States', ' Married-civ-spouse'}), confidence=0.9156626506024096, lift=2.222482161656334), OrderedStatistic(items_base=frozenset({' United-States', ' White', ' Married-civ-spouse'}), items_add=frozenset({' Husband', 'CL_-272.25-0.0'}), confidence=0.8128342245989305, lift=2.1675579322638145), OrderedStatistic(items_base=frozenset({' United-States', 'CL_-272.25-0.0', ' Married-civ-spouse'}), items_add=frozenset({' Husband', ' White'}), confidence=0.7855297157622738, lift=2.212759762710631), OrderedStatistic(items_base=frozenset({' White', 'CL_-272.25-0.0', ' Married-civ-spouse'}), items_add=frozenset({' Husband', ' United-States'}), confidence=0.7958115183246073, lift=2.2291639168756507), OrderedStatistic(items_base=frozenset({' Husband', ' United-States', ' White', 'CL_-272.25-0.0'}), items_add=frozenset({' Married-civ-spouse'}), confidence=1.0, lift=2.1739130434782608), OrderedStatistic(items_base=frozenset({' United-States', ' White', 'CL_-272.25-0.0', ' Married-civ-spouse'}), items_add=frozenset({' Husband'}), confidence=0.8710601719197708, lift=2.1885933967833435)])

In [27]:
df_apriori.drop(['final-weight','education-num','marital-status','relationship',
                 'capital-gain','capital-loos', 'native-country'], inplace=True, axis=1)

In [28]:
transacoes = []
for i in range(df_apriori.shape[0]):
    transacoes.append([str(df_apriori.values[i, j]) for j in range(df_apriori.shape[1])])

In [35]:
rules = apriori(transacoes, min_support = 0.2, min_confidence = 0.2, min_lift=0.9)
result = list(rules)
len(result)

23

In [36]:
print(*result, sep='\n\n')

RelationRecord(items=frozenset({' <=50K'}), support=0.756, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({' <=50K'}), confidence=0.756, lift=1.0)])

RelationRecord(items=frozenset({' >50K'}), support=0.244, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({' >50K'}), confidence=0.244, lift=1.0)])

RelationRecord(items=frozenset({' HS-grad'}), support=0.308, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({' HS-grad'}), confidence=0.308, lift=1.0)])

RelationRecord(items=frozenset({' Private'}), support=0.689, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({' Private'}), confidence=0.689, lift=1.0)])

RelationRecord(items=frozenset({' Some-college'}), support=0.222, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({' Some-college'}), confidence=0.222, lift=1.0)])

RelationRecord(items=frozenset({' White'}), support=0.842, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({' White'}), confidence=0.842, lift=1.0)])

RelationRecord(items=frozenset({'HW_37.75-43.875'}), support=0.513, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'HW_37.75-43.875'}), confidence=0.513, lift=1.0)])

RelationRecord(items=frozenset({' <=50K', ' HS-grad'}), support=0.257, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({' <=50K', ' HS-grad'}), confidence=0.257, lift=1.0), OrderedStatistic(items_base=frozenset({' <=50K'}), items_add=frozenset({' HS-grad'}), confidence=0.33994708994708994, lift=1.1037243180100322), OrderedStatistic(items_base=frozenset({' HS-grad'}), items_add=frozenset({' <=50K'}), confidence=0.8344155844155845, lift=1.1037243180100325)])

RelationRecord(items=frozenset({' <=50K', ' Private'}), support=0.537, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({' <=50K', ' Private'}), confidence=0.537, lift=1.0), OrderedStatistic(items_base=frozenset({' <=50K'}), items_add=frozenset({' Private'}), confidence=0.7103174603174603, lift=1.0309397101849933), OrderedStatistic(items_base=frozenset({' Private'}), items_add=frozenset({' <=50K'}), confidence=0.779390420899855, lift=1.0309397101849933)])

RelationRecord(items=frozenset({' <=50K', ' White'}), support=0.621, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({' <=50K', ' White'}), confidence=0.621, lift=1.0), OrderedStatistic(items_base=frozenset({' <=50K'}), items_add=frozenset({' White'}), confidence=0.8214285714285714, lift=0.9755683746182559), OrderedStatistic(items_base=frozenset({' White'}), items_add=frozenset({' <=50K'}), confidence=0.7375296912114014, lift=0.9755683746182559)])

RelationRecord(items=frozenset({' <=50K', 'HW_37.75-43.875'}), support=0.398, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({' <=50K', 'HW_37.75-43.875'}), confidence=0.398, lift=1.0), OrderedStatistic(items_base=frozenset({' <=50K'}), items_add=frozenset({'HW_37.75-43.875'}), confidence=0.5264550264550265, lift=1.0262281217446911), OrderedStatistic(items_base=frozenset({'HW_37.75-43.875'}), items_add=frozenset({' <=50K'}), confidence=0.7758284600389864, lift=1.0262281217446911)])

RelationRecord(items=frozenset({' White', ' >50K'}), support=0.221, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({' White', ' >50K'}), confidence=0.221, lift=1.0), OrderedStatistic(items_base=frozenset({' >50K'}), items_add=frozenset({' White'}), confidence=0.9057377049180328, lift=1.0756979868385188), OrderedStatistic(items_base=frozenset({' White'}), items_add=frozenset({' >50K'}), confidence=0.26247030878859856, lift=1.0756979868385188)])

RelationRecord(items=frozenset({' Private', ' HS-grad'}), support=0.229, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({' Private', ' HS-grad'}), confidence=0.229, lift=1.0), OrderedStatistic(items_base=frozenset({' HS-grad'}), items_add=frozenset({' Private'}), confidence=0.7435064935064936, lift=1.0791095696756077), OrderedStatistic(items_base=frozenset({' Private'}), items_add=frozenset({' HS-grad'}), confidence=0.3323657474600871, lift=1.0791095696756074)])

RelationRecord(items=frozenset({' HS-grad', ' White'}), support=0.258, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({' HS-grad', ' White'}), confidence=0.258, lift=1.0), OrderedStatistic(items_base=frozenset({' HS-grad'}), items_add=frozenset({' White'}), confidence=0.8376623376623377, lift=0.9948483820217787), OrderedStatistic(items_base=frozenset({' White'}), items_add=frozenset({' HS-grad'}), confidence=0.30641330166270786, lift=0.9948483820217788)])

RelationRecord(items=frozenset({' Private', ' White'}), support=0.579, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({' Private', ' White'}), confidence=0.579, lift=1.0), OrderedStatistic(items_base=frozenset({' Private'}), items_add=frozenset({' White'}), confidence=0.8403483309143687, lift=0.9980383977605329), OrderedStatistic(items_base=frozenset({' White'}), items_add=frozenset({' Private'}), confidence=0.6876484560570071, lift=0.9980383977605328)])

RelationRecord(items=frozenset({' Private', 'HW_37.75-43.875'}), support=0.379, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({' Private', 'HW_37.75-43.875'}), confidence=0.379, lift=1.0), OrderedStatistic(items_base=frozenset({' Private'}), items_add=frozenset({'HW_37.75-43.875'}), confidence=0.5500725689404935, lift=1.072266216258272), OrderedStatistic(items_base=frozenset({'HW_37.75-43.875'}), items_add=frozenset({' Private'}), confidence=0.7387914230019493, lift=1.072266216258272)])

RelationRecord(items=frozenset({' White', 'HW_37.75-43.875'}), support=0.413, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({' White', 'HW_37.75-43.875'}), confidence=0.413, lift=1.0), OrderedStatistic(items_base=frozenset({' White'}), items_add=frozenset({'HW_37.75-43.875'}), confidence=0.4904988123515439, lift=0.9561380357729901), OrderedStatistic(items_base=frozenset({'HW_37.75-43.875'}), items_add=frozenset({' White'}), confidence=0.8050682261208576, lift=0.9561380357729901)])

RelationRecord(items=frozenset({' <=50K', ' HS-grad', ' White'}), support=0.211, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({' <=50K', ' HS-grad', ' White'}), confidence=0.211, lift=1.0), OrderedStatistic(items_base=frozenset({' <=50K'}), items_add=frozenset({' HS-grad', ' White'}), confidence=0.27910052910052907, lift=1.0817849965136785), OrderedStatistic(items_base=frozenset({' HS-grad'}), items_add=frozenset({' <=50K', ' White'}), confidence=0.685064935064935, lift=1.1031641466424076), OrderedStatistic(items_base=frozenset({' White'}), items_add=frozenset({' <=50K', ' HS-grad'}), confidence=0.2505938242280285, lift=0.9750732460234572), OrderedStatistic(items_base=frozenset({' <=50K', ' HS-grad'}), items_add=frozenset({' White'}), confidence=0.8210116731517509, lift=0.9750732460234572), OrderedStatistic(items_base=frozenset({' <=50K', ' White'}), items_add=frozenset({' HS-grad'}), confidence=0.3397745571658615, lift=1.1031641466424076), OrderedStatistic(items_base=frozenset({' HS-grad', ' White'}), items_add=frozenset({' <=50K'}), confidence=0.817829457364341, lift=1.0817849965136785)])

RelationRecord(items=frozenset({' <=50K', ' Private', ' White'}), support=0.443, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({' <=50K', ' Private', ' White'}), confidence=0.443, lift=1.0), OrderedStatistic(items_base=frozenset({' <=50K'}), items_add=frozenset({' Private', ' White'}), confidence=0.5859788359788359, lift=1.0120532573036891), OrderedStatistic(items_base=frozenset({' Private'}), items_add=frozenset({' <=50K', ' White'}), confidence=0.6429608127721336, lift=1.035363627652389), OrderedStatistic(items_base=frozenset({' White'}), items_add=frozenset({' <=50K', ' Private'}), confidence=0.5261282660332541, lift=0.9797546853505663), OrderedStatistic(items_base=frozenset({' <=50K', ' Private'}), items_add=frozenset({' White'}), confidence=0.8249534450651769, lift=0.9797546853505664), OrderedStatistic(items_base=frozenset({' <=50K', ' White'}), items_add=frozenset({' Private'}), confidence=0.713365539452496, lift=1.0353636276523892), OrderedStatistic(items_base=frozenset({' Private', ' White'}), items_add=frozenset({' <=50K'}), confidence=0.765112262521589, lift=1.0120532573036891)])

RelationRecord(items=frozenset({' <=50K', ' Private', 'HW_37.75-43.875'}), support=0.308, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({' <=50K', ' Private', 'HW_37.75-43.875'}), confidence=0.308, lift=1.0), OrderedStatistic(items_base=frozenset({' <=50K'}), items_add=frozenset({' Private', 'HW_37.75-43.875'}), confidence=0.4074074074074074, lift=1.0749535815498876), OrderedStatistic(items_base=frozenset({' Private'}), items_add=frozenset({' <=50K', 'HW_37.75-43.875'}), confidence=0.4470246734397678, lift=1.123177571456703), OrderedStatistic(items_base=frozenset({'HW_37.75-43.875'}), items_add=frozenset({' <=50K', ' Private'}), confidence=0.6003898635477583, lift=1.1180444386364212), OrderedStatistic(items_base=frozenset({' <=50K', ' Private'}), items_add=frozenset({'HW_37.75-43.875'}), confidence=0.5735567970204841, lift=1.1180444386364212), OrderedStatistic(items_base=frozenset({' <=50K', 'HW_37.75-43.875'}), items_add=frozenset({' Private'}), confidence=0.7738693467336683, lift=1.123177571456703), OrderedStatistic(items_base=frozenset({' Private', 'HW_37.75-43.875'}), items_add=frozenset({' <=50K'}), confidence=0.8126649076517151, lift=1.0749535815498876)])

RelationRecord(items=frozenset({' <=50K', ' White', 'HW_37.75-43.875'}), support=0.314, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({' <=50K', ' White', 'HW_37.75-43.875'}), confidence=0.314, lift=1.0), OrderedStatistic(items_base=frozenset({' <=50K'}), items_add=frozenset({' White', 'HW_37.75-43.875'}), confidence=0.41534391534391535, lift=1.0056753398157756), OrderedStatistic(items_base=frozenset({' White'}), items_add=frozenset({' <=50K', 'HW_37.75-43.875'}), confidence=0.37292161520190026, lift=0.9369889829193473), OrderedStatistic(items_base=frozenset({'HW_37.75-43.875'}), items_add=frozenset({' <=50K', ' White'}), confidence=0.6120857699805068, lift=0.9856453622874506), OrderedStatistic(items_base=frozenset({' <=50K', ' White'}), items_add=frozenset({'HW_37.75-43.875'}), confidence=0.5056360708534622, lift=0.9856453622874506), OrderedStatistic(items_base=frozenset({' <=50K', 'HW_37.75-43.875'}), items_add=frozenset({' White'}), confidence=0.7889447236180904, lift=0.9369889829193473), OrderedStatistic(items_base=frozenset({' White', 'HW_37.75-43.875'}), items_add=frozenset({' <=50K'}), confidence=0.7602905569007264, lift=1.0056753398157756)])

RelationRecord(items=frozenset({' Private', ' White', 'HW_37.75-43.875'}), support=0.305, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({' Private', ' White', 'HW_37.75-43.875'}), confidence=0.305, lift=1.0), OrderedStatistic(items_base=frozenset({' Private'}), items_add=frozenset({' White', 'HW_37.75-43.875'}), confidence=0.4426705370101597, lift=1.071841493971331), OrderedStatistic(items_base=frozenset({' White'}), items_add=frozenset({' Private', 'HW_37.75-43.875'}), confidence=0.36223277909738716, lift=0.9557593116026046), OrderedStatistic(items_base=frozenset({'HW_37.75-43.875'}), items_add=frozenset({' Private', ' White'}), confidence=0.594541910331384, lift=1.0268426776016997), OrderedStatistic(items_base=frozenset({' Private', ' White'}), items_add=frozenset({'HW_37.75-43.875'}), confidence=0.5267702936096719, lift=1.0268426776016994), OrderedStatistic(items_base=frozenset({' Private', 'HW_37.75-43.875'}), items_add=frozenset({' White'}), confidence=0.8047493403693932, lift=0.9557593116026047), OrderedStatistic(items_base=frozenset({' White', 'HW_37.75-43.875'}), items_add=frozenset({' Private'}), confidence=0.738498789346247, lift=1.071841493971331)])

RelationRecord(items=frozenset({' <=50K', ' Private', ' White', 'HW_37.75-43.875'}), support=0.248, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({' <=50K', ' Private', ' White', 'HW_37.75-43.875'}), confidence=0.248, lift=1.0), OrderedStatistic(items_base=frozenset({' <=50K'}), items_add=frozenset({' Private', ' White', 'HW_37.75-43.875'}), confidence=0.328042328042328, lift=1.075548616532223), OrderedStatistic(items_base=frozenset({' Private'}), items_add=frozenset({' <=50K', ' White', 'HW_37.75-43.875'}), confidence=0.3599419448476053, lift=1.1463119262662589), OrderedStatistic(items_base=frozenset({' White'}), items_add=frozenset({' <=50K', ' Private', 'HW_37.75-43.875'}), confidence=0.29453681710213775, lift=0.956288367214733), OrderedStatistic(items_base=frozenset({'HW_37.75-43.875'}), items_add=frozenset({' <=50K', ' Private', ' White'}), confidence=0.4834307992202729, lift=1.0912659124611126), OrderedStatistic(items_base=frozenset({' <=50K', ' Private'}), items_add=frozenset({' White', 'HW_37.75-43.875'}), confidence=0.46182495344506513, lift=1.1182202262592378), OrderedStatistic(items_base=frozenset({' <=50K', ' White'}), items_add=frozenset({' Private', 'HW_37.75-43.875'}), confidence=0.3993558776167472, lift=1.0537094396220241), OrderedStatistic(items_base=frozenset({' <=50K', 'HW_37.75-43.875'}), items_add=frozenset({' Private', ' White'}), confidence=0.6231155778894472, lift=1.0761927079265063), OrderedStatistic(items_base=frozenset({' Private', ' White'}), items_add=frozenset({' <=50K', 'HW_37.75-43.875'}), confidence=0.4283246977547496, lift=1.0761927079265063), OrderedStatistic(items_base=frozenset({' Private', 'HW_37.75-43.875'}), items_add=frozenset({' <=50K', ' White'}), confidence=0.6543535620052771, lift=1.0537094396220243), OrderedStatistic(items_base=frozenset({' White', 'HW_37.75-43.875'}), items_add=frozenset({' <=50K', ' Private'}), confidence=0.6004842615012107, lift=1.1182202262592378), OrderedStatistic(items_base=frozenset({' <=50K', ' Private', ' White'}), items_add=frozenset({'HW_37.75-43.875'}), confidence=0.5598194130925508, lift=1.0912659124611126), OrderedStatistic(items_base=frozenset({' <=50K', ' Private', 'HW_37.75-43.875'}), items_add=frozenset({' White'}), confidence=0.8051948051948052, lift=0.9562883672147331), OrderedStatistic(items_base=frozenset({' <=50K', ' White', 'HW_37.75-43.875'}), items_add=frozenset({' Private'}), confidence=0.7898089171974522, lift=1.1463119262662587), OrderedStatistic(items_base=frozenset({' Private', ' White', 'HW_37.75-43.875'}), items_add=frozenset({' <=50K'}), confidence=0.8131147540983606, lift=1.075548616532223)])